import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/components/nav/top-nav";
import SideMenu from "@/components/side-menu";
import {NextHeroRouter} from "@/components/router-provider";

export const metadata: Metadata = {
  title: "Overflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={'h-full'} suppressHydrationWarning>
      <body className={'flex flex-col h-full bg-stone-200 dark:bg-background text-foreground'}>
      <NextHeroRouter>
      <TopNav />
      <div className={'flex grow overflow-auto'}>
          <aside className={'bases-1/6 shrink-0 border-r border-neutral-500 pt-20 sticky top-0 px-6'}>
              <SideMenu />
          </aside>
          <main className={'flex-1 pt-20 h-full'}>
              {children}
          </main>
          <aside className={'basis-1/4 shrink-0 px-6 pt-20 bg-stone-300 dark:bg-background sticky top-0'}>
              Right content
          </aside>
      </div>
      </NextHeroRouter>
      </body>
    </html>
  );
}
